"""Persistent embedding cache for SecureCodeRAG."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

import numpy as np


class EmbeddingCacheError(RuntimeError):
    """Base exception for embedding cache failures."""


class EmbeddingCache:
    """File-backed cache for deterministic embedding vectors."""

    CACHE_VERSION = 1

    def __init__(
        self,
        cache_dir: str | Path,
        *,
        namespace: str = "default",
    ) -> None:
        """Initialize an embedding cache.

        Args:
            cache_dir: Directory in which cache files are stored.
            namespace: Logical namespace separating different caches.

        Raises:
            EmbeddingCacheError: If the cache configuration is invalid.
        """
        if not namespace or not namespace.strip():
            raise EmbeddingCacheError("namespace must be non-empty.")

        self._cache_dir = Path(cache_dir)
        self._namespace = namespace.strip()
        self._memory: dict[str, np.ndarray] = {}

        self._cache_dir.mkdir(parents=True, exist_ok=True)

    @property
    def cache_dir(self) -> Path:
        """Return the cache directory."""
        return self._cache_dir

    @property
    def namespace(self) -> str:
        """Return the cache namespace."""
        return self._namespace

    @property
    def size(self) -> int:
        """Return the number of entries currently held in memory."""
        return len(self._memory)

    def build_key(
        self,
        text: str,
        *,
        model_name: str,
        model_config: dict[str, Any] | None = None,
    ) -> str:
        """Build a deterministic cache key.

        The key includes the model identity and configuration so vectors
        generated by different embedding configurations cannot collide.
        """
        if not isinstance(text, str):
            raise EmbeddingCacheError("text must be a string.")

        if not model_name or not model_name.strip():
            raise EmbeddingCacheError("model_name must be non-empty.")

        payload = {
            "cache_version": self.CACHE_VERSION,
            "namespace": self._namespace,
            "model_name": model_name.strip(),
            "model_config": self._canonicalize(model_config or {}),
            "text": text,
        }

        serialized = json.dumps(
            payload,
            ensure_ascii=False,
            sort_keys=True,
            separators=(",", ":"),
        ).encode("utf-8")

        digest = hashlib.sha256(serialized).hexdigest()

        return f"emb-{digest}"

    def get(self, key: str) -> np.ndarray | None:
        """Return a cached vector if available.

        Args:
            key: Cache key.

        Returns:
            A copied NumPy vector, or ``None`` when absent.
        """
        self._validate_key(key)

        vector = self._memory.get(key)

        if vector is not None:
            return vector.copy()

        path = self._entry_path(key)

        if not path.exists():
            return None

        try:
            with np.load(path, allow_pickle=False) as data:
                vector = np.asarray(data["embedding"], dtype=np.float32)
        except Exception as exc:
            raise EmbeddingCacheError(
                f"Unable to read cache entry {key!r}: {exc}"
            ) from exc

        self._validate_vector(vector, key)

        self._memory[key] = vector.copy()

        return vector.copy()

    def put(self, key: str, embedding: np.ndarray) -> None:
        """Store an embedding under a cache key.

        Args:
            key: Cache key.
            embedding: One-dimensional embedding vector.
        """
        self._validate_key(key)

        vector = np.asarray(embedding, dtype=np.float32)

        self._validate_vector(vector, key)

        path = self._entry_path(key)
        temporary_path = path.with_suffix(".tmp.npz")

        try:
            with temporary_path.open("wb") as handle:
                np.savez_compressed(
                    handle,
                    embedding=vector,
                )

            temporary_path.replace(path)
        except Exception as exc:
            if temporary_path.exists():
                temporary_path.unlink()

            raise EmbeddingCacheError(
                f"Unable to write cache entry {key!r}: {exc}"
            ) from exc

        self._memory[key] = vector.copy()

    def contains(self, key: str) -> bool:
        """Return whether a cache entry exists."""
        self._validate_key(key)

        return key in self._memory or self._entry_path(key).exists()

    def delete(self, key: str) -> bool:
        """Delete one cache entry.

        Returns:
            ``True`` when an entry was deleted, otherwise ``False``.
        """
        self._validate_key(key)

        deleted = self._memory.pop(key, None) is not None
        path = self._entry_path(key)

        if path.exists():
            try:
                path.unlink()
            except OSError as exc:
                raise EmbeddingCacheError(
                    f"Unable to delete cache entry {key!r}: {exc}"
                ) from exc

            deleted = True

        return deleted

    def clear(self) -> int:
        """Clear all entries belonging to this namespace.

        Returns:
            Number of deleted cache entries.
        """
        deleted_count = 0

        for path in self._cache_dir.glob("emb-*.npz"):
            try:
                path.unlink()
            except OSError as exc:
                raise EmbeddingCacheError(
                    f"Unable to delete cache file {path}: {exc}"
                ) from exc

            deleted_count += 1

        self._memory.clear()

        return deleted_count

    def stats(self) -> dict[str, Any]:
        """Return basic cache statistics."""
        disk_entries = len(list(self._cache_dir.glob("emb-*.npz")))

        return {
            "cache_version": self.CACHE_VERSION,
            "namespace": self._namespace,
            "cache_dir": str(self._cache_dir),
            "memory_entries": len(self._memory),
            "disk_entries": disk_entries,
        }

    def _entry_path(self, key: str) -> Path:
        """Return the filesystem path for a cache key."""
        return self._cache_dir / f"{key}.npz"

    @staticmethod
    def _validate_key(key: str) -> None:
        """Validate a cache key."""
        if not isinstance(key, str) or not key.strip():
            raise EmbeddingCacheError("Cache key must be a non-empty string.")

        if Path(key).name != key:
            raise EmbeddingCacheError("Cache key must not contain path separators.")

    @staticmethod
    def _validate_vector(vector: np.ndarray, key: str) -> None:
        """Validate a cached embedding vector."""
        if vector.ndim != 1:
            raise EmbeddingCacheError(
                f"Cache entry {key!r} must contain a one-dimensional vector."
            )

        if vector.size == 0:
            raise EmbeddingCacheError(
                f"Cache entry {key!r} contains an empty vector."
            )

        if not np.isfinite(vector).all():
            raise EmbeddingCacheError(
                f"Cache entry {key!r} contains NaN or infinite values."
            )

    @classmethod
    def _canonicalize(cls, value: Any) -> Any:
        """Convert configuration values into deterministic JSON-safe data."""
        if isinstance(value, dict):
            return {
                str(key): cls._canonicalize(item)
                for key, item in sorted(value.items(), key=lambda item: str(item[0]))
            }

        if isinstance(value, (list, tuple)):
            return [cls._canonicalize(item) for item in value]

        if isinstance(value, Path):
            return str(value)

        if isinstance(value, np.generic):
            return value.item()

        if value is None or isinstance(value, (str, int, float, bool)):
            return value

        return str(value)